library(readxl)
download.file("http://ryanwomack.com/data/PharmaDemo.xls", "mydata.xls")
mydata<-read_excel("mydata.xls")
names(mydata)
attach(mydata)
summary(Weight)
library(ggplot2)
ggplot(mydata, aes(Weight, Age))+geom_point()
summary(lm(Age~Weight))
ggplot(mydata, aes(Weight, Age))+geom_point()+stat_smooth()
